### ISSUE TITLE
inputEmail is not iterable

### ISSUE THREAD

**Issue by Sandlayth** [HSleymn/projet#1]
When I try to run the code, I get the following error:
```
main.js:27 Uncaught TypeError: inputMail is not iterable
    at HTMLInputElement.verification (main.js:27:24)
```
Indeed, the variable inputMail is not iterable as it is an HTML element.
If you want to get the input entered by the user, you have to use the value attribute.

```
inputMail = document.getElementById("mailInput").value;
```

Do not hesitate to use the console of your browser (usually f12) and to run the code interactively to see how it behaves.

**Comment by HSleymn** [comment]
Thank you for the answer, it helped me and solved the problem.

But i still dont understand: what is the difference between this : 
`inputMail = document.getElementById("mailInput")`
and this :
`inputMail = document.getElementById("mailInput").value;`

I mean, i know right it's not the same thing, but i dont understand. Doesn't the first one take the value of the input ?

**Comment by HSleymn** [comment]
Okay thank you very much.
